"""Services package for business logic."""

from app.services.aquarium import (
    AquariumAccessDeniedError,
    AquariumError,
    AquariumNotFoundError,
    AquariumOwnerRequiredError,
    check_access,
    create_aquarium,
    delete_aquarium,
    get_aquarium,
    get_aquarium_with_fish,
    list_user_aquariums,
    update_aquarium,
)
from app.services.auth import (
    AuthError,
    EmailAlreadyExistsError,
    InvalidCredentialsError,
    InvalidRefreshTokenError,
    login_user,
    logout,
    refresh_tokens,
    register_user,
)
from app.services.family import (
    FamilyError,
    MemberLimitExceededError,
    create_invite,
    get_family_members,
)
from app.services.gamification import (
    ACHIEVEMENT_DEFINITIONS,
    AchievementDefinition,
    GamificationError,
    NoFreezeAvailableError,
    StreakNotFoundError,
    UserStats,
    check_achievements,
    get_achievements,
    get_or_create_streak,
    get_streak,
    share_achievement,
    update_streak,
    use_freeze,
)
from app.services.purchase import (
    InvalidReceiptError,
    PurchaseError,
    RevenueCatAPIError,
    RevenueCatNotConfiguredError,
    UserNotFoundError,
    get_subscription_status,
    process_webhook,
    restore_purchases,
    revert_to_free,
    update_subscription_status,
)
from app.services.species import (
    SpeciesAlreadyExistsError,
    SpeciesError,
    SpeciesNotFoundError,
    create_species,
    delete_species,
    get_popular_species,
    get_species,
    list_species,
    search_species,
    update_species,
)

__all__ = [
    # Aquarium
    "AquariumAccessDeniedError",
    "AquariumError",
    "AquariumNotFoundError",
    "AquariumOwnerRequiredError",
    "check_access",
    "create_aquarium",
    "delete_aquarium",
    "get_aquarium",
    "get_aquarium_with_fish",
    "list_user_aquariums",
    "update_aquarium",
    # Family
    "FamilyError",
    "MemberLimitExceededError",
    "create_invite",
    "get_family_members",
    # Auth
    "AuthError",
    "EmailAlreadyExistsError",
    "InvalidCredentialsError",
    "InvalidRefreshTokenError",
    "login_user",
    "logout",
    "refresh_tokens",
    "register_user",
    # Species
    "SpeciesAlreadyExistsError",
    "SpeciesError",
    "SpeciesNotFoundError",
    "create_species",
    "delete_species",
    "get_popular_species",
    "get_species",
    "list_species",
    "search_species",
    "update_species",
    # Gamification
    "ACHIEVEMENT_DEFINITIONS",
    "AchievementDefinition",
    "GamificationError",
    "NoFreezeAvailableError",
    "StreakNotFoundError",
    "UserStats",
    "check_achievements",
    "get_achievements",
    "get_or_create_streak",
    "get_streak",
    "share_achievement",
    "update_streak",
    "use_freeze",
    # Purchase
    "InvalidReceiptError",
    "PurchaseError",
    "RevenueCatAPIError",
    "RevenueCatNotConfiguredError",
    "UserNotFoundError",
    "get_subscription_status",
    "process_webhook",
    "restore_purchases",
    "revert_to_free",
    "update_subscription_status",
]
